[package]
name = "reqq"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { git = "https://github.com/zivergetech/reqwest", branch = "update-jun-2024", features = ["json", "blocking"] }
serde_json = "1.0.127" # Needed for async runtime
